name: Build & Push App Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    uses: serkanbulutgenc/django-k8s-test/.github/workflows/test.yml@main
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install the doctl tools
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{secrets.DO_ACCESS_TOKEN}}
      - name: Build & Tag the App Image
        run: |
          docker build -t registry.digitalocean.com/k8s-test-docr/k8s-django:latest \
          -t registry.digitalocean.com/k8s-test-docr/k8s-django:${{github.sha::7}} -f compose/local/django/Dockerfile webapp
      - name: Push the images to DOCR
        run: |
          doctl registry login --expiry-seconds 1200
          docker push registry.digitalocean.com/k8s-test-docr/k8s-django:latest
          docker push registry.digitalocean.com/k8s-test-docr/k8s-django::${{github.sha::7}} 
          
          
          
  
